### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL)

### ISSUE THREAD

**Issue by niazche** [opencobra/memote#717] opened 2021-04-24 06:43 UTC
Hello:

I was trying to run my SBML file and the memote is giving me an error showing "WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL)". I am attaching my sbml format model here as a text file.

Please let me know the issue and potential solution.

Thank you

[New Text Document.txt](https://github.com/opencobra/memote/files/6369076/New.Text.Document.txt)

**Comment by niazche** [comment] 2021-04-24 06:56
Just to be clear, I was using the moemote.io website. Thanks!

**Comment by Midnighter** [comment] 2021-04-24 18:32
Thank you for attaching the model. That will make it possible to find the cause for the error. Have you already tried to use memote from the command line on your model? That is, only if you are comfortable working on the command line or with Python, of course.

**Comment by niazche** [comment] 2021-04-24 19:01
Thanks for the reply. No, I am not very comfortable with that. Is it an issue withe memote.io website?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Midnighter** [comment] 2021-04-24 22:31
Your model is quite large with 4460 metabolites and 4042 reactions. Maybe @carrascomj, you could check the logs on the server but I can guess at potential problems:

1. Due to the size of your model the server may run out of memory.
2. The size is generally not a problem for memote but on memote.io we can only use the open source GLPK solver due to licensing restrictions. This mathematical solver is a lot slower than commercial solver for some types of problems. Thus your job may have run out of time.

In any case, I ran memote on my laptop and I have [attached the report here](https://github.com/opencobra/memote/files/6370867/report.zip) for you. It took a long time (1 h) and quite a bit of memory (8 GB) indeed. It shows that a lot of the reactions in your model are recognized as biomass reactions. This is a problem with your model. I can see that a large number of exchange and transport reactions have the name `"biomass"`. That doesn't make sense to me and confuses memote. I would change those names to something more specific. Additionally, you could add the SBO term [SBO:0000629](https://www.ebi.ac.uk/sbo/main/SBO:0000629) to your true `Root_Biomass_MB` reaction. You also have a compartment named biomass which I have not seen being done before. 

@carrascomj maybe we should skip the informative consistency checks by default on memote.io? 🤔

**Comment by niazche** [comment] 2021-04-25 01:01
Thank you so much for your help! I will keep your suggestion in mind while building my next model.

Sincerely,

Niaz
________________________________

**Comment by carrascomj** [comment] 2021-04-25 14:17
If those tests are the problem, maybe we can do it since it doesn't affect the score. Do we have an estimate of the dimensions of the stoichiometry matrix that _cannot_ be run on memote.io (we cannot deterministically measure that for the additional inconsistency tests but maybe for other tests that are memory intensive)? I believe setting a warning on the web app about the size of the model would help the users.

**Comment by Midnighter** [comment] 2021-04-25 19:52
Sorry I don't currently have such estimates since resources were downsized quite a bit after the end of the DeCaF project.

I had another idea, since recently the COIN-OR CBC interface became available in optlang, we could use that solver for MIP tests. I haven't run any benchmarks, though, comparing it to GLPK.

**Comment by Midnighter** [comment] 2021-04-26 09:11
I'm closing this issue. Let's continue the discussion elsewhere.

**Closed by Midnighter** 2021-04-26 09:11 UTC
