### ISSUE TITLE
Wrong formulas/calculations of memote scores

### ISSUE THREAD

**Issue by mckohnen** [opencobra/memote#730] opened 2022-02-23 03:27 UTC
Hi,

When I calculated the results according to the formulas provided in the html report I noticed that the score of "Annotation - Metabolites" (63.23%) does not match the displayed results (81.83%) (see screenshot1). Same goes for "Annotation - Genes" and "Annotation - Reactions". Unlike in the formula, where every single value is weighted equally, I figured that memote first calculates normalized scores for the parameters "Annotations Per Database" and "Annotation Conformity Per Database" and then uses these summarized scores to calculate the metabolites/genes/reactions annotation scores. Thus, the displayed formulas need be corrected. In this case for example, the formula would be as follows:

<img width="527" alt="memote_metabolic_annotation_corrected_formula" src="https://user-images.githubusercontent.com/57352546/155257075-3de75d0d-ccdf-4c5d-ae62-bee8f1aa2f7b.png">

Furthermore I also noticed that total score (69.94%) (see screenshot2) does not match the calculations according to the displayed formula (66.94%). However, here I really have no idea what is going wrong... Could you maybe have a look at this?

Best regards
Max

P.S.: I installed the latest stable version of memote using pip.

![memote_metabolic_annotation_result](https://user-images.githubusercontent.com/57352546/155255071-ea042762-375d-40c3-98f6-a75ca993dcba.png)

![memote_total_score](https://user-images.githubusercontent.com/57352546/155255369-e89f5158-6a00-453e-87fe-49006cfe4741.png)

**Comment by Midnighter** [comment] 2022-02-23 08:56
Duplicate of #716. If you have the time to fix it, any help is appreciated.

**Closed by Midnighter** 2022-02-23 08:56 UTC
