### ISSUE TITLE
Potentially fix `find_transport_reactions`

### ISSUE THREAD

**Issue by siddC** [opencobra/memote#395] opened 2018-03-19 17:05 UTC
#### Problem description

`find_transport_reactions` is a function that is used throughout the codebase or in functions/tests that are used throughout the codebase. However, it currently requires a valid formula field and cannot detect transport reactions via PTS. We may want to look into changing this function to be more robust.

**Comment by ChristianLieven** [comment] 2018-03-21 07:57
To a degree this is a duplicate of #390

**Closed** 2018-03-21 07:57 UTC
